"""a

Revision ID: 0846f8edf167
Revises: 66ae87baa901
Create Date: 2023-06-14 18:21:14.218839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0846f8edf167'
down_revision = '66ae87baa901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mimetype', sa.String(), nullable=False))
        batch_op.drop_column('mimtype')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mimtype', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('mimetype')

    # ### end Alembic commands ###
