"""fixing not null constraint failed

Revision ID: 2360f93d38a8
Revises: 4a63deeaccbe
Create Date: 2023-06-28 09:52:48.518438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2360f93d38a8'
down_revision = '4a63deeaccbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
