"""added friend to notification table

Revision ID: 40382c32b550
Revises: 2e9865956d24
Create Date: 2023-06-20 13:59:20.725310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40382c32b550'
down_revision = '2e9865956d24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('friendship_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_notifications_friendship_id_friends'), 'friends', ['friendship_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_notifications_friendship_id_friends'), type_='foreignkey')
        batch_op.drop_column('friendship_id')

    # ### end Alembic commands ###
