"""adding boolean column to likes

Revision ID: 48ef3b766eab
Revises: 2360f93d38a8
Create Date: 2023-06-28 14:37:13.172421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48ef3b766eab'
down_revision = '2360f93d38a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
