"""a

Revision ID: 72f5347fd5c3
Revises: 78978d718a91
Create Date: 2023-06-15 10:27:50.476352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72f5347fd5c3'
down_revision = '78978d718a91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_post_content_posts', type_='foreignkey')
        batch_op.drop_column('post_content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_content', sa.VARCHAR(), nullable=True))
        batch_op.create_foreign_key('fk_users_post_content_posts', 'posts', ['post_content'], ['content'])

    # ### end Alembic commands ###
