"""a

Revision ID: 78978d718a91
Revises: 8c81d3ce152d
Create Date: 2023-06-15 10:27:13.621228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78978d718a91'
down_revision = '8c81d3ce152d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('post_content',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('post_content',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
