"""a

Revision ID: 8c81d3ce152d
Revises: 8f1992a36fe2
Create Date: 2023-06-15 10:26:42.383444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c81d3ce152d'
down_revision = '8f1992a36fe2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_content', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_users_post_content_posts'), 'posts', ['post_content'], ['content'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_post_content_posts'), type_='foreignkey')
        batch_op.drop_column('post_content')

    # ### end Alembic commands ###
