"""messing with comments table

Revision ID: e35a7c80a1a3
Revises: eb063a5fcfb1
Create Date: 2023-06-23 11:30:04.776849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e35a7c80a1a3'
down_revision = 'eb063a5fcfb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('comments')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comments', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
