"""recovered tables

Revision ID: eb063a5fcfb1
Revises: 40382c32b550
Create Date: 2023-06-22 10:15:50.418279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb063a5fcfb1'
down_revision = '40382c32b550'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friend_requests')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('banner_picture', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('banner_picture')

    op.create_table('friend_requests',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sender_id', sa.INTEGER(), nullable=True),
    sa.Column('recipient_id', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], name='fk_friend_requests_recipient_id_users'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name='fk_friend_requests_sender_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
